spring:
  security:
    user:
      name: john
      password: passwd
      roles: user

management:
  server:
    port: 8081

logging:
  level:
    org.springframework.web: debug
    org.springframework.security: debug
    #io.netty: trace